"""Tests for exporter.export_csv."""
import sys, os
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', 'src'))

import pandas as pd
import pytest
from exporter import export_csv


RESULTS = [
    {'url': 'https://example.com', 'status_code': 200, 'latency_ms': 123.45, 'state': 'Healthy'},
    {'url': 'https://example.com/gone', 'status_code': 404, 'latency_ms': 87.1, 'state': 'Broken'},
]


def test_export_csv_writes_given_path(tmp_path):
    target = tmp_path / 'report.csv'
    path = export_csv(RESULTS, str(target))
    assert path == str(target)
    assert target.exists()


def test_export_csv_contents_and_columns(tmp_path):
    target = tmp_path / 'report.csv'
    export_csv(RESULTS, str(target))
    df = pd.read_csv(target)
    assert list(df.columns) == ['id', 'url', 'status_code', 'latency_ms', 'state', 'timestamp']
    assert df['url'].tolist() == [r['url'] for r in RESULTS]
    assert df['state'].tolist() == ['Healthy', 'Broken']


def test_export_csv_index_starts_at_one(tmp_path):
    target = tmp_path / 'report.csv'
    export_csv(RESULTS, str(target))
    df = pd.read_csv(target)
    assert df['id'].tolist() == [1, 2]


def test_export_csv_adds_timestamp_column(tmp_path):
    target = tmp_path / 'report.csv'
    export_csv(RESULTS, str(target))
    df = pd.read_csv(target)
    assert df['timestamp'].nunique() == 1
    pd.to_datetime(df['timestamp'])  # raises if not parseable


def test_export_csv_ignores_extra_keys(tmp_path):
    target = tmp_path / 'report.csv'
    export_csv([dict(RESULTS[0], extra='dropped')], str(target))
    df = pd.read_csv(target)
    assert 'extra' not in df.columns


def test_export_csv_handles_missing_status_code(tmp_path):
    target = tmp_path / 'report.csv'
    export_csv(
        [{'url': 'https://slow.example.com', 'status_code': None,
          'latency_ms': 10000, 'state': 'Timeout'}],
        str(target),
    )
    df = pd.read_csv(target)
    assert pd.isna(df['status_code'].iloc[0])
    assert df['state'].iloc[0] == 'Timeout'


def test_export_csv_empty_results_raises():
    with pytest.raises(ValueError, match='No results to export'):
        export_csv([])


def test_export_csv_none_results_raises():
    with pytest.raises(ValueError, match='No results to export'):
        export_csv(None)


def test_export_csv_autogenerates_path(tmp_path, monkeypatch):
    # Point exporter's module dir at tmp_path so exports/ lands there.
    monkeypatch.setattr('exporter.__file__', str(tmp_path / 'src' / 'exporter.py'))
    path = export_csv(RESULTS)
    assert os.path.dirname(path).endswith('exports')
    assert os.path.basename(path).startswith('scan_')
    assert path.endswith('.csv')
    assert os.path.exists(path)


def test_export_csv_autogenerated_name_uses_timestamp(tmp_path, monkeypatch):
    monkeypatch.setattr('exporter.__file__', str(tmp_path / 'src' / 'exporter.py'))
    from datetime import datetime
    path = export_csv(RESULTS)
    stamp = os.path.basename(path)[len('scan_'):-len('.csv')]
    datetime.strptime(stamp, '%Y%m%d_%H%M%S')  # raises if malformed
